substitutions:
  device_id: 
  device_name: 
  platform: ESP8266
  board: esp01_1m
  ip_address: !secret _ip
  ota_pwd: !secret _ota_pwd
  api_pwd: !secret _api_pwd
  ap_wifi_pwd: !secret _ap_wifi_pwd

esphome:
  <<: !include common/esphome.yaml

<<: !include common/common_tuya_dimmer.yaml
<<: !include common/logger/logger_none.yaml

binary_sensor:
  - !include common/binary_sensor/status.yaml

sensor:
  - !include common/sensor/uptime.yaml
  - !include common/sensor/wifi.yaml

switch:
  - !include common/switch/restart.yaml

text_sensor:
  - !include common/text_sensor/version.yaml
  - !include common/text_sensor/wifi.yaml