substitutions:
  device_id: family_room_light
  device_name: Family Room Light
  platform: ESP8266
  board: esp01_1m
  ip_address: !secret family_room_light_ip
  ota_pwd: !secret family_room_light_ota_pwd
  api_pwd: !secret family_room_light_api_pwd
  ap_wifi_pwd: !secret family_room_light_ap_wifi_pwd

esphome:
  <<: !include common/esphome.yaml

<<: !include common/common_tuya_dimmer.yaml
<<: !include common/logger/logger_none.yaml

binary_sensor:
  - !include common/binary_sensor/status.yaml

sensor:
  - !include common/sensor/uptime.yaml
  - !include common/sensor/wifi.yaml

switch:
  - !include common/switch/restart.yaml

text_sensor:
  - !include common/text_sensor/version.yaml
  - !include common/text_sensor/wifi.yaml
