substitutions:
  device_id: kitchen_table_light
  device_name: Kitchen Table Light
  platform: ESP8266
  board: esp01_1m
  ip_address: !secret kitchen_table_light_ip
  ota_pwd: !secret kitchen_table_light_ota_pwd
  api_pwd: !secret kitchen_table_light_api_pwd
  ap_wifi_pwd: !secret kitchen_table_light_ap_wifi_pwd

esphome:
  <<: !include common/esphome.yaml

<<: !include common/common_tuya_feit_dimmer.yaml
<<: !include common/logger/logger_tuya_no_log.yaml

binary_sensor:
  - !include common/binary_sensor/status.yaml

sensor:
  - !include common/sensor/uptime.yaml
  - !include common/sensor/wifi.yaml

switch:
  - !include common/switch/restart.yaml

text_sensor:
  - !include common/text_sensor/version.yaml
  - !include common/text_sensor/wifi.yaml