substitutions:
  device_id: living_room_lights
  device_name: Living Room Lights
  platform: ESP8266
  board: esp01_1m
  ip_address: !secret living_room_lights_ip
  ota_pwd: !secret living_room_lights_ota_pwd
  api_pwd: !secret living_room_lights_api_pwd
  ap_wifi_pwd: !secret living_room_lights_ap_wifi_pwd
  day_brightness: "1"
  night_brightness: ".03"
  night_auto_off_time: 15min
  linked_lights: ""

<<: !include common/device_tuya_dimmer.yaml
