substitutions:
  device_id: patio_lights
  device_name: Patio Lights
  platform: ESP8266
  board: d1_mini
  ip_address: !secret patio_lights_ip
  ota_pwd: !secret patio_lights_ota_pwd
  api_pwd: !secret patio_lights_api_pwd
  ap_wifi_pwd: !secret patio_lights_ap_wifi_pwd

esphome:
  <<: !include common/esphome.yaml

<<: !include common/common.yaml
<<: !include common/logger/logger_none.yaml

binary_sensor:
  - !include common/binary_sensor/status.yaml

sensor:
  - !include common/sensor/uptime.yaml
  - !include common/sensor/wifi.yaml

switch:
  - !include common/switch/restart.yaml
  - platform: gpio
    id: patio_lights
    name: "Patio Lights"
    icon: mdi:lightbulb
    pin: D1
    inverted: false

text_sensor:
  - !include common/text_sensor/version.yaml
  - !include common/text_sensor/wifi.yaml