substitutions:
  device_id: basement_bathroom_light_fan
  device_name: Basement Bathroom Light and Fan
  platform: ESP8266
  board: esp01_1m
  ip_address: !secret basement_bathroom_light_fan_ip
  ota_pwd: !secret basement_bathroom_light_fan_ota_pwd
  api_pwd: !secret basement_bathroom_light_fan_api_pwd
  ap_wifi_pwd: !secret basement_bathroom_light_fan_ap_wifi_pwd

packages:
  device_base: !include ../packages/device_base.yaml

binary_sensor:
  - platform: gpio
    id: light_button
    pin:
      number: 12
      mode: INPUT_PULLUP
    on_press:
      then:
        - light.toggle: the_light
  - platform: gpio
    id: fan_button
    pin:
      number: 3
      mode: INPUT_PULLUP
    on_press:
      then:
        - fan.toggle: the_fan

fan:
  - platform: binary
    id: the_fan
    output: fan_output
    name: "Basement Bathroom Fan"

light:
  - platform: binary
    id: the_light
    name: "Basement Bathroom Light"
    output: light_output

output:
  - platform: gpio
    id: fan_output
    pin: 4
  - platform: gpio
    id: light_output
    pin: 13

status_led:
  pin:
    number: 0
    inverted: true
