substitutions:
  device_id: basement_bath_shower_light_heat
  device_name: Basement Bathroom Shower Light and Heater
  platform: ESP8266
  board: esp01_1m
  ip_address: !secret basement_bathroom_shower_light_heater_ip
  ota_pwd: !secret basement_bathroom_shower_light_heater_ota_pwd
  api_pwd: !secret basement_bathroom_shower_light_heater_api_pwd
  ap_wifi_pwd: !secret basement_bathroom_shower_light_heater_ap_wifi_pwd

packages:
  device_base: !include ../packages/device_base.yaml

binary_sensor:
  - platform: gpio
    id: light_button
    pin:
      number: 12
      mode: INPUT_PULLUP
    on_press:
      then:
        - light.toggle: the_light
  - platform: gpio
    id: heater_button
    pin:
      number: 3
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: heater

light:
  - platform: binary
    id: the_light
    name: "Basement Shower Light"
    output: light_output

output:
  - platform: gpio
    id: light_output
    pin: 13

status_led:
  pin:
    number: 0
    inverted: true

switch:
  - platform: gpio
    id: heater
    name: "Basement Bathroom Heater"
    icon: mdi:radiator
    pin: 4
