substitutions:
  device_id: front_lights
  device_name: Front Lights
  platform: ESP8266
  board: esp01_1m
  ip_address: !secret front_lights_ip
  ota_pwd: !secret front_lights_ota_pwd
  api_pwd: !secret front_lights_api_pwd
  ap_wifi_pwd: !secret front_lights_ap_wifi_pwd
  day_brightness: "1"
  night_brightness: "1"
  day_auto_off_minutes: "30"
  night_auto_off_minutes: "15"
  linked_lights: ""
  double_tap_on_stays_on: "true"

script:
  - id: startup
    then:
      - lambda: |-
          TuyaLight->add_double_tap_on_callback([]() { TuyaLight->set_auto_off_minutes(0); });

<<: !include ../core/device_tuya_dimmer.yaml

