substitutions:
  device_id: patio_lights
  device_name: Patio Lights
  platform: ESP8266
  board: d1_mini
  ip_address: !secret patio_lights_ip
  ota_pwd: !secret patio_lights_ota_pwd
  api_pwd: !secret patio_lights_api_pwd
  ap_wifi_pwd: !secret patio_lights_ap_wifi_pwd

packages:
  device_base: !include ../packages/device_base.yaml

light:
  - platform: binary
    name: "Patio Lights"
    output: patio_lights_output

output:
  - platform: gpio
    id: patio_lights_output
    pin: D1
