substitutions:
  device_id: scripture_of_the_day_1
  device_name: Scripture of the Day #1
  platform: ESP8266
  board: nodemcuv2
  ip_address: !secret master_bath_humidity_temp_sensor_ip
  ota_pwd: !secret master_bath_humidity_temp_sensor_ota_pwd
  api_pwd: !secret master_bath_humidity_temp_sensor_api_pwd
  ap_wifi_pwd: !secret master_bath_humidity_temp_sensor_ap_wifi_pwd

esphome:
  <<: !include ../core/esphome.yaml
  on_boot:
    priority: -100
    then:
      - http_request.get:
          url: "https://beta.ourmanna.com/api/v1/get/?format=json&order=random"
          verify_ssl: false
      - lambda: |-
          auto json = http_request_httprequestcomponent->get_string();

<<: !include ../components/logger/logger_debug.yaml

<<: !include ../core/wifi_api_ota.yaml

http_request:

text_sensor:
  - platform: template
    id: scripture

  - platform: template
    id: reference